#!/usr/bin/env bash
# doctor.sh — read-only health check of an agent-ops setup.
# Usage: doctor.sh            (config from ${AGENT_OPS_CONFIG:-$HOME/.claude/agent-ops/config.env})
# Prints a PASS/WARN/FAIL table. Exit 1 on any FAIL. No network (loopback only), no writes, never prints secret values.
set -u

CONFIG="${AGENT_OPS_CONFIG:-$HOME/.claude/agent-ops/config.env}"
HERE="$(cd "$(dirname "$0")" && pwd)"
FAILS=0 WARNS=0
ROWS=""

row() {   # row STATUS CHECK DETAIL
  case "$1" in FAIL) FAILS=$((FAILS+1));; WARN) WARNS=$((WARNS+1));; esac
  ROWS="${ROWS}$(printf '%-4s | %-22s | %s' "$1" "$2" "$3")
"
}
have() { command -v "$1" >/dev/null 2>&1; }
need_bin() {   # need_bin BIN LEVEL WHY
  if have "$1"; then row PASS "$1" "$(command -v "$1")"; else row "$2" "$1" "not found — $3"; fi
}

# ---- config ----
if [ ! -f "$CONFIG" ]; then
  row FAIL "config" "missing $CONFIG — run /agent-ops:init"
  printf '%-4s | %-22s | %s\n' STAT CHECK DETAIL; printf '%s' "$ROWS"
  echo "doctor: 1 FAIL — run /agent-ops:init"; exit 1
fi
row PASS "config" "$CONFIG"
perm=$(ls -l "$CONFIG" | cut -c8-10)
[ "$perm" = "---" ] || row WARN "config perms" "readable by others — chmod 600 \"$CONFIG\""
. "$HERE/lib/cos-os.sh"   # cos_source_config, cos_path_list, COS_OS / COS_WSL detection
cos_source_config "$CONFIG" || { row FAIL "config parse" "sourcing failed — fix the syntax"; }
. "$HERE/lib/cos-os.sh"   # re-run detection for anything the config left empty
grep -q "$(printf '\r')" "$CONFIG" && row WARN "config line ends" "CRLF — tolerated, but save it with LF line ends"
[ -z "${COS_LAUNCH_DIRS:-}" ] || COS_LAUNCH_DIRS=$(cos_path_list "$COS_LAUNCH_DIRS")
[ -z "${COS_DIR:-}" ] || COS_DIR=$(cos_path "$COS_DIR")

# ---- platform ----
case "$COS_OS" in
  mac) row PASS "os" "macOS";;
  linux) if [ "$COS_WSL" = 1 ]; then row PASS "os" "linux (WSL) — the recommended Windows setup"; else row PASS "os" "linux"; fi;;
  windows) row WARN "os" "windows (Git Bash/MSYS) — untested; load-check approximate, no cmux, no multi-account; WSL2 recommended";;
esac
if [ "$COS_OS" = windows ] || [ "$COS_WSL" = 1 ]; then
  if grep -qE '^[^#]*[A-Za-z]:\\' "$CONFIG"; then
    row WARN "path style" "config has C:\\ paths — use /c/Users/… (Git Bash) or /mnt/c/… (WSL)"
  else row PASS "path style" "POSIX paths"; fi
  crlf=$(grep -l "$(printf '\r')" "$HERE"/*.sh "$HERE"/lib/*.sh "$HERE/../../../hooks/"*.sh 2>/dev/null | wc -l | tr -d ' ')
  if [ "${crlf:-0}" -gt 0 ]; then row FAIL "script line ends" "$crlf script(s) have CRLF — git config core.autocrlf false, then re-clone"
  else row PASS "script line ends" "LF"; fi
fi

# ---- state dir ----
if [ -z "${COS_DIR:-}" ]; then
  row FAIL "COS_DIR" "not set in config"
elif [ ! -d "$COS_DIR" ]; then
  row FAIL "COS_DIR" "$COS_DIR does not exist — run /agent-ops:init"
elif [ ! -w "$COS_DIR" ]; then
  row FAIL "COS_DIR" "$COS_DIR not writable"
else
  row PASS "COS_DIR" "$COS_DIR"
  for d in tasks briefs; do
    [ -d "$COS_DIR/$d" ] && row PASS "$d/" "present" || row WARN "$d/" "missing — created on first script run"
  done
  for f in STATE.md GOALS.md; do
    [ -f "$COS_DIR/$f" ] && row PASS "$f" "present" || row WARN "$f" "missing — run /agent-ops:init"
  done
  if [ -f "$COS_DIR/GOALS.md" ]; then
    n=$(grep -cE '^### [A-Z][0-9]+ · ' "$COS_DIR/GOALS.md" 2>/dev/null || true)
    if [ "${n:-0}" -eq 0 ]; then row WARN "goals" "no '### G1 · <outcome>' block — spawn.sh needs one"
    elif grep -q '<outcome' "$COS_DIR/GOALS.md"; then row WARN "goals" "placeholder goal still present — write your own"
    else row PASS "goals" "$n goal(s)"; fi
  fi
fi
out="${COS_OUTSTANDING:-${COS_DIR:-}/Outstanding.md}"
[ -f "$out" ] && row PASS "Outstanding" "$out" || row WARN "Outstanding" "missing $out — regenerated by outstanding.sh"

# ---- core tools ----
need_bin claude FAIL "install Claude Code"
need_bin git FAIL "install git"
if cos_python -c 'import sys; sys.exit(sys.version_info[0] < 3)' >/dev/null 2>&1; then row PASS "python" "$COS_PYTHON ($(cos_python -c 'import platform; print(platform.python_version())' 2>/dev/null))"
else row FAIL "python" "no python 3 (tried python3, python, py -3) — task files are parsed by scripts/lib/tasks.py; or set COS_PYTHON"; fi
need_bin jq WARN "some scripts use it"
[ -f "$HERE/spawn.sh" ] && row PASS "plugin scripts" "$HERE" || row FAIL "plugin scripts" "spawn.sh not next to doctor.sh"

# ---- launcher ----
case "${COS_LAUNCHER:-}" in
  tmux) need_bin tmux FAIL "COS_LAUNCHER=tmux — install it or set print";;
  cmux) if [ "$COS_OS" = mac ]; then need_bin cmux FAIL "COS_LAUNCHER=cmux — install it or set print"; else row FAIL "launcher" "cmux is macOS only — set tmux, wt or print"; fi;;
  wt) if wtb=$(cos_wt_bin); then row PASS "launcher" "wt (Windows Terminal: $wtb)"; else row FAIL "launcher" "COS_LAUNCHER=wt but wt.exe not found — install Windows Terminal or set print"; fi;;
  print) row WARN "launcher" "print launcher: workers will not start by themselves; install tmux (or use wt/cmux)";;
  "") if have tmux; then row WARN "launcher" "COS_LAUNCHER unset — tmux will be used"
      elif cos_wt_bin >/dev/null 2>&1; then row WARN "launcher" "COS_LAUNCHER unset — wt (Windows Terminal) will be used"
      else row WARN "launcher" "COS_LAUNCHER unset — print will be used: workers will not start by themselves; install tmux (or use wt/cmux)"; fi;;
  *) row FAIL "launcher" "COS_LAUNCHER=$COS_LAUNCHER — must be tmux|cmux|wt|print";;
esac

# ---- launch dirs, prefix, capacity ----
if [ -z "${COS_LAUNCH_DIRS:-}" ]; then
  row FAIL "COS_LAUNCH_DIRS" "empty — spawn.sh refuses every --dir"
else
  ok=0 bad=""
  IFS=: read -r -a dirs <<<"$COS_LAUNCH_DIRS"
  for d in "${dirs[@]}"; do [ -d "$d" ] && ok=$((ok+1)) || bad="$bad $d"; done
  if [ -n "$bad" ]; then row WARN "COS_LAUNCH_DIRS" "$ok ok, missing:$bad"; else row PASS "COS_LAUNCH_DIRS" "$ok dir(s)"; fi
fi
case "${COS_MACHINE_PREFIX:-}" in
  [a-z]) row PASS "COS_MACHINE_PREFIX" "$COS_MACHINE_PREFIX";;
  *) row FAIL "COS_MACHINE_PREFIX" "'${COS_MACHINE_PREFIX:-}' — must be one lowercase letter";;
esac
case "${COS_MAX_LOCAL_SESSIONS:-}" in
  ''|*[!0-9]*) row WARN "COS_MAX_LOCAL_SESSIONS" "not a number — default used";;
  *) row PASS "COS_MAX_LOCAL_SESSIONS" "$COS_MAX_LOCAL_SESSIONS";;
esac

case "${COS_SESSIONS_DIR:-}" in
  "") row WARN "COS_SESSIONS_DIR" "unset — session logs go to ./sessions in each repo (or .agent-ops.json sessionsDir)";;
  /*|"~"*|[A-Za-z]:*) d="${COS_SESSIONS_DIR/#\~/$HOME}"
     [ -d "$d" ] && row PASS "COS_SESSIONS_DIR" "$COS_SESSIONS_DIR" || row WARN "COS_SESSIONS_DIR" "$COS_SESSIONS_DIR missing — created on first /agent-ops:session-start";;
  *) row PASS "COS_SESSIONS_DIR" "$COS_SESSIONS_DIR (relative to each repo root)";;
esac

# ---- add-ons (only when configured) ----
if [ -n "${COS_TELEGRAM_TARGET:-}" ]; then
  need_bin hermes FAIL "Telegram add-on needs hermes"
else row PASS "addon telegram" "off"; fi

if [ -n "${COS_JIRA_BASE:-}" ]; then
  case "$COS_JIRA_BASE" in https://*) row PASS "addon jira" "base set";; *) row WARN "addon jira" "COS_JIRA_BASE should start https://";; esac
  [ -n "${JIRA_API_TOKEN:-}" ] && row PASS "JIRA_API_TOKEN" "set in env (value not shown)" || row WARN "JIRA_API_TOKEN" "not in this env — export it from your secret store"
  [ -n "${COS_JIRA_JQL:-}" ] || row WARN "addon jira" "JQL empty — Outstanding shows no Jira items"
else row PASS "addon jira" "off"; fi

if [ -n "${COS_REMOTE_HOST_KEY:-}" ]; then
  need_bin ssh FAIL "remote runner needs ssh"
  [ -f "${COS_INVENTORY:-/nonexistent}" ] && row PASS "remote inventory" "$COS_INVENTORY" || row FAIL "remote inventory" "COS_INVENTORY not a file"
  [ -n "${COS_REMOTE_USER:-}" ] || row FAIL "remote user" "COS_REMOTE_USER empty"
  case "${COS_REMOTE_MACHINE_PREFIX:-}" in [a-z]) row PASS "remote prefix" "$COS_REMOTE_MACHINE_PREFIX";; *) row FAIL "remote prefix" "must be one lowercase letter";; esac
  [ "${COS_REMOTE_MACHINE_PREFIX:-}" = "${COS_MACHINE_PREFIX:-}" ] && row FAIL "remote prefix" "same letter as this machine"
else row PASS "addon remote runner" "off"; fi

[ "${COS_DEFAULT_ACCOUNT:-a}" = a ] || [ "$COS_OS" = mac ] || row WARN "addon multi-account" "macOS only (Keychain) — skipped here"
case "${COS_DEFAULT_ACCOUNT:-a}" in
  auto) [ -f "${COS_ACCOUNTS:-${COS_DIR:-}/accounts.md}" ] && row PASS "addon multi-account" "auto, accounts file present" || row WARN "addon multi-account" "auto, no accounts file yet — add logins with account-add.sh";;
  *) row PASS "addon multi-account" "off (account ${COS_DEFAULT_ACCOUNT:-a})";;
esac
if [ -n "${COS_VAULT_PORT:-}" ]; then   # loopback-only check; the proxy returns route names, never secrets
  case "$COS_VAULT_PORT" in *[!0-9]*) row FAIL "addon keyproxy" "COS_VAULT_PORT must be a port number";;
  *) kp=$(bash "$HERE/addons/keyproxy/keyproxy-health" "$COS_VAULT_PORT" 2>/dev/null)
     if [ $? -eq 0 ]; then row PASS "addon keyproxy" "${kp#keyproxy: }"
     else
       hint="start your vault"; [ "$(uname -s)" = Darwin ] && hint="install the bundled proxy: sudo bash $HERE/addons/keyproxy/install.sh"
       row WARN "addon keyproxy" "nothing healthy on 127.0.0.1:$COS_VAULT_PORT — needs: [vault] tasks wait; $hint"; fi;;
  esac
else row PASS "addon keyproxy" "off"; fi

[ "${COS_ADHD_MODE:-0}" = 1 ] && row PASS "addon adhd mode" "on" || row PASS "addon adhd mode" "off"

# ---- report ----
printf '%-4s | %-22s | %s\n' STAT CHECK DETAIL
printf '%s\n' "-----+------------------------+------------------------------"
printf '%s' "$ROWS"
if [ "$FAILS" -gt 0 ]; then echo "doctor: $FAILS FAIL, $WARNS WARN"; exit 1; fi
echo "doctor: OK ($WARNS WARN)"
